-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMVAkXHa3SccTZqxc
IBciHQ+NB6r+JxUJShxOBOBR8MigCgYIKoZIzj0DAQehRANCAAS7oL41hac1zYcn
PMndM2ojV/33NRzmlkKF0Q/obP9Hp+lr6Wbp7C4EjGXfhhkCbMILP9h5cBGPVwMa
mqTlBR4M
-----END PRIVATE KEY-----